### ISSUE TITLE
Package install in Raptor

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/msgraph-sdk-typescript#491] opened 2024-02-01 21:16 UTC

**Comment by rkodev** [comment] 2024-07-01 08:28
@sebastienlevert @andrueastman could you share some more information on this issue

**Comment by andrueastman** [comment] 2024-07-01 09:12
@rkodev I'm not clear on this one. I'd suggest holding this one off for now till at least Seb gets back to get clarity on outcomes and priority....

**Comment by baywet** [comment] 2024-07-02 12:09
I'm pretty sure he meant to capture the fact we need to support the package installation in Raptor as the API surface is now divided across multiple packages.

**Comment by baywet** [comment] 2024-11-28 12:37
closing as duplicate of this issue. https://github.com/microsoftgraph/msgraph-sdk-typescript-core/issues/13

**Closed by baywet** 2024-11-28 12:37 UTC
Labels: ToTriage

**Comment by rkodev** [comment] 2025-02-17 07:07
Closed by https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/3600
